version: '3.4'

services:
  bluefoxgloveapi:
    container_name: bluefoxgloveapi
    image: ${DOCKER_REGISTRY-}bluefoxgloveapi
    ports:
      - "8080:443"
      - "8000:80"
    build:
      context: .
      dockerfile: BlueFoxGloveAPI/Dockerfile
    networks:
       - bluefoxglovedemonetwork

networks:
  bluefoxglovedemonetwork:
    external: true